### ISSUE TITLE
Passing a document name for SSH

### ISSUE THREAD

**Issue by jValdron** [rewindio/aws-connect#8]
Hey, would it be possible to allow us to pass the document name when we start an SSH session? It would be needed in our use case.

I did create a branch with this change here: https://github.com/jValdron/aws-connect/tree/jValdron-ssh-document

**Comment by dnorth98** [comment]
It essentially does that if the action is "document" (`-a document`).  The idea behind the `ssh` option is to give you a shell and the `document` option is to run a document.

```bash
if [ "${action}" == "ssh" ]; then
  echo "Establishing session manager connection to ${instance_name} (${instance_id})"
  aws ssm start-session \
    --target "${instance_id}" \
    --region "${aws_region}" \
    --profile "${aws_profile}"
::
::
::
elif [ "${action}" == "document" ]; then
::
  aws_command="aws ssm send-command \
    --instance-ids ${instance_id} \
    --document-name \"${document_name}\" \
    --comment \"Document run using aws-connect\" \
    --output text \
    --region \"${aws_region}\" \
    --profile \"${aws_profile}\" \
    --cloud-watch-output-config '{\"CloudWatchLogGroupName\":\"${cloudwatch_group}\",\"CloudWatchOutputEnabled\":true}' \
    --query \"Command.CommandId\""
```

So the document option is the same command (ie. still calling `send-command` but also specifying a document.  I'm basically saying the option already exists :)

**Comment by dnorth98** [comment]
Oh wait..I see, you want to be able to pass a document to start-session.  Yeah, I don't see any harm in that.  Send us a Pull Request and we can merge that in.

**Comment by dnorth98** [comment]
Closed by https://github.com/rewindio/aws-connect/pull/9
